package web

import (
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

// dist/ and docs-dist/ are generated by server/build.sh and never committed, so
// these run in two different embedded states: against the .gitkeep stubs (fresh
// clone, the CI `backend` job) and against a real build (the CI `server` job).
// Everything here must hold in both — that dual guarantee is the whole point of
// the placeholder path, so the tests assert it rather than assuming a build.

func TestNewSucceedsWithoutBuild(t *testing.T) {
	// The regression this guards: New() used to hard-fail when dist held no
	// index.html, which made `go run ./cmd/abacad` impossible without first
	// building the frontend.
	spa, err := New()
	if err != nil {
		t.Fatalf("New() must succeed whether or not a build is embedded: %v", err)
	}
	if spa == nil {
		t.Fatal("New() returned a nil SPA with no error")
	}
}

func TestServesIndexAtRoot(t *testing.T) {
	spa, err := New()
	if err != nil {
		t.Fatalf("New(): %v", err)
	}

	rec := httptest.NewRecorder()
	spa.ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/", nil))

	if rec.Code != http.StatusOK {
		t.Errorf("GET /: status = %d, want %d", rec.Code, http.StatusOK)
	}
	if ct := rec.Header().Get("Content-Type"); !strings.HasPrefix(ct, "text/html") {
		t.Errorf("GET /: Content-Type = %q, want text/html", ct)
	}
	if rec.Body.Len() == 0 {
		t.Error("GET /: empty body")
	}
}

func TestUnknownPathFallsBackToIndex(t *testing.T) {
	// Client-side routes (e.g. /settings) must survive a hard refresh.
	spa, err := New()
	if err != nil {
		t.Fatalf("New(): %v", err)
	}

	rec := httptest.NewRecorder()
	spa.ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/settings", nil))

	if rec.Code != http.StatusOK {
		t.Errorf("GET /settings: status = %d, want %d (SPA fallback)", rec.Code, http.StatusOK)
	}
}

func TestPlaceholderOnlyWithoutRealBuild(t *testing.T) {
	spa, err := New()
	if err != nil {
		t.Fatalf("New(): %v", err)
	}

	rec := httptest.NewRecorder()
	spa.ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/", nil))
	body := rec.Body.String()

	// HaveApp() is the switch the startup hint in cmd/abacad keys off, so it has
	// to agree with what is actually being served.
	if spa.HaveApp() {
		if strings.Contains(body, "No dashboard build embedded") {
			t.Error("HaveApp() is true but the placeholder is being served")
		}
	} else if !strings.Contains(body, "No dashboard build embedded") {
		t.Errorf("HaveApp() is false but the placeholder was not served; got:\n%s", body)
	}
}

func TestDocsHandlerBuildsInBothStates(t *testing.T) {
	// Docs() must return a usable handler even with no Astro build embedded --
	// serving 404s there is fine, panicking or nil is not.
	h := Docs()
	if h == nil {
		t.Fatal("Docs() returned nil")
	}

	rec := httptest.NewRecorder()
	h.ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/docs/", nil))

	if HaveDocs() {
		if rec.Code != http.StatusOK {
			t.Errorf("GET /docs/ with a build embedded: status = %d, want %d", rec.Code, http.StatusOK)
		}
	} else if rec.Code != http.StatusNotFound {
		t.Errorf("GET /docs/ without a build: status = %d, want %d", rec.Code, http.StatusNotFound)
	}
}
